### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by radaniba** [bioinform/somaticseq#13]
Is the Training dataset for somaticseq available somewhere ?

**Comment by ltfang-bina** [comment]
In paper, we used Stage 3 of the DREAM Challenge training data for whole genome sequencing of coverage ~ 30X. 

This page describes how to download DREAM Challenge data: 
https://www.synapse.org/#!Synapse:syn312572/wiki/60702

Basically, you need GeneTorrent to download DREAM Challenge data. Stage 3 does not need special authorization access, so that makes it easier. 

Once you install GeneTorrent and downloaded the public authorization token, the **URLs for GeneTorrent** are:

- Normal: https://dream.annailabs.com/cghub/data/analysis/download/b19d76a0-a487-4c50-8f9c-3b4d5e53239d
- Tumor: https://dream.annailabs.com/cghub/data/analysis/download/8fe6fc33-2daf-4393-929f-7c3493d04bef

For our paper, we re-aligned those reads again with BWA MEM, and then did GATK Indel Realigment and then Base Quality Recalibration to obtain the new BAM files (i.e., GATK Best Practices).

**Comment by radaniba** [comment]
Hi Li,

Yes I am familiar with DREAM but maybe I didn't express what I meant properly, The dream challenge data does not provide somatic mutations positions afaik right ? you downloaded this data **to predict and not to train** and this **is not what I meant**. I want to access training dataset not testing dataset.

**Comment by ltfang-bina** [comment]
DREAM Challenge releases the mutation positions after each stage closes:
https://www.synapse.org/#!Synapse:syn2177211

SomaticSeq needs to separate out the SNVs and INDELs and the other stuff. So for Stage 3, I've actually uploaded them here as well: https://github.com/bioinform/somaticseq/tree/master/DREAM_Stage_3

I have done 2 different things in the paper:
1) Use Stage 2 as training, and Stage 3 for prediction (i.e., Fig 2 in the paper). 
2) Cross validation: randomly split Stage 3 data into 2 halves, and one for training and one for prediction (Fig 3 in the paper). 

Stage 3 was used for training in the Table 1 results.

**Comment by radaniba** [comment]
Thank you Li, that is very helpful
