### ISSUE TITLE
question about indel calls by "NUM_TOOLS=0"

### ISSUE THREAD

**Issue by hongenxu** [bioinform/somaticseq#14]
Hi Litai,

I used SSeq_merged.vcf2tsv.py to merge indel calls by four callers, CGA VarScan2 VarDict LoFreq, and then used SSeq_tsv2vcf.py to change TSV file to VCF file. In the output VCF file, I found some indel calls with KEY "NUM_TOOLS=0". I thought all the INDEL calls in the output file should be called by one caller. Would you please help me?

`1       28796   .       T       TATCCCATCCCACCCCATCCCATTCCATCCCATCCTGTATTCCATCCCCATCCCATTCCAATCCCATCCTTATTCCATCCCCATCCCATCCCATCCCATCCCATCCC 0.0000  REJECT  MVDL=0,0,0,0;NUM_TOOLS=0        GT:DP4:CD4:refMQ:altMQ:refBQ:altBQ:refNM:altNM:fetSB:fetCD:zMQ:zBQ:VAF      0/0:3,0,0,0:3,0,0,0:53.3333:.:36.3333:.:1.33333:.:1.00:1.00:.:.:0       0/0:2,0,0,0:2,0,0,0:60:.:35.5:.:2:.:1.00:1.00:.:.:0`

Best,
Hongen

**Comment by ltfang-bina** [comment]
I included some calls in the combined call set that were not classified as a PASS/SOMATIC call by the original caller. Some of the calls did not pass all the filters set by the callers.
Those calls may be included, but I used the caller's original classification in the VCF file, so it's possible to have NUM_TOOLS=0 if it's only there because it's a LowQual call by a caller.

**Comment by hongenxu** [comment]
thanks for clarification. 

Hongen
