### ISSUE TITLE
Is oncoscore available after the removal of score_Somatic.Variants.py in version newer than 2.1.2

### ISSUE THREAD

**Issue by hongenxu** [bioinform/somaticseq#15]
Hi Litai,

score_Somatic.Variants.py calculate a oncoscore for SNV and Indel calls. Since version 2.1.2, score_Somatic.Variants.py has been removed. Do you have any plan to incorporate it into the newer version of SomaticSEQ? Or this score is not useful anymore?

Best regards,
Hongen

**Comment by ltfang-bina** [comment]
It's not useful anymore. It hasn't been useful for a while, but I've kept it there. 

The score_Somatic.Variants.py was created before SomaticSeq. It consolidates a bunch of information such as caller classification, caller's output metrics, dbSNP, COSMIC, etc. It also calculated a score based on hard cutoffs that we no longer use. Earlier SomaticSeq versions extracted those things from the output of score_Somatic.Variants.py. 

Since later versions, all those features are directly extracted from each caller's VCF files as well as dbSNP and COSMIC VCF files using the SSeq_merged.tsv2vcf.py script. The input file can be the one after GATK CombineVariants. We don't need extra step between that and SSeq_merged.tsv2vcf.py any longer.

**Comment by hongenxu** [comment]
thanks
