### ISSUE TITLE
submitSomaticSniper: unable to open file /mnt/<path-to-RESULTS>/1/1.bed

### ISSUE THREAD

**Issue by 0xaf1f** [bioinform/somaticseq#45]
I am trying to run `$SOMATICSEQ_HOME/utilities/singularities/submit_callers_multiThreads.sh` analogously to the docker method described at https://github.com/bioinform/somaticseq/tree/master/utilities/dockered_pipelines, but it doesn't get past SomaticSniper, which fails in the end with these messages (I redacted the full path name for the issue here):

```
bash: /mnt//path-to/RESULTS/1/SomaticSniper.vcf: No such file or directory
Error: Unable to open file /mnt//path-to/RESULTS/1/1.bed. Exiting.
```

My RESULTS folder doesn't have a `1` directory; the files sought by the program are at the top-level:

```
$ ls RESULTS/
10.bed  12.bed  14.bed  16.bed  2.bed  4.bed  6.bed  8.bed  genome.bed  SomaticSniper.vcf
11.bed  13.bed  15.bed  1.bed   3.bed  5.bed  7.bed  9.bed  logs
```

**Comment by ltfang-bina** [comment]
Can you show me the full submit_callers_multiThreads.sh command (redact the full paths if you'd like to)?

**Comment by 0xaf1f** [comment]
Sure. It's basically the same as the example. I just changed threads and action (to bash, since we don't run SGE).

```bash
$SOMATICSEQ_HOME/utilities/singularities/submit_callers_multiThreads.sh \
--normal-bam      /fdb/DREAM/SMC/synthetic.challenge.set1.normal.v2.bam \
--tumor-bam       /fdb/DREAM/SMC/synthetic.challenge.set1.tumor.v2.bam \
--human-reference /fdb/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa \
--output-dir      /abspath/to//RESULTS \
--dbsnp           /fdb/dbSNP/organisms/human_9606_b150_GRCh37p13/00-All.vcf.gz \
--threads         36 \
--action          bash \
--mutect2 --varscan2 --somaticsniper --vardict --muse --lofreq --scalpel --strelka --somaticseq
```

**Comment by ltfang-bina** [comment]
I think I know what the problem is. 
What the submit_callers_multiThreads.sh script intends to do, is to
1) Create the SomaticSniper run script that takes the whole bam files, since SomaticSniper does not take partial bam input. The run script has a final step that splits its own VCF into partial VCF files into the directories named 1, 2, 3....
The problem is, those directories are not created until the SomaticSniper script is created. It didn't expect SomaticSniper to finish running. 

2) *After* SomaticSniper script is created, then directories 1, 2, 3, ..., will be created and BED files created in them, then all the other mutation calling scripts are also created. 

I think you can try "--action echo," and then run those .cmd files as bash scripts after they're created. 

Alternatively, I can put the SomaticSniper script after, instead of before, all those region-splitting steps. I'll probably do that now and make a mini-release. Having "--action bash" is not something I foresaw.

**Comment by ltfang-bina** [comment]
I made the latest commit where I put SomaticSniper **after** all the other callers, so it should avoid your problem. 
Still, waiting for each mutation callers to finish one-by-one is going to take a while. It won't be parallelized if you do "--action bash," since it'll just bash each separate script one by one.

**Comment by 0xaf1f** [comment]
Ah, ok. That kind of brings me to a related question I was having. `--action bash` was not something ideal anyway, because it would run each caller in serial, but I was testing to see if I could get the whole pipeline to run within a single job allocation.

We could do an `--action sbatch`, but then we'd need to add analogous comments to the created job scripts to define the sbatch parameters like how you do for qsub.

**Comment by 0xaf1f** [comment]
> I made the latest commit where I put SomaticSniper **after** all the other callers, so it should avoid your problem.

Ok, thanks. For some reason, I thought echo would just do a dry run. I didn't realize it still made the scripts. I'll probably go that route and use a workflow manager to run the pipeline on the cluster.

**Comment by ltfang-bina** [comment]
Yeah, that should work. 
My scripts in this repo don't do dependencies. 
All the individual mutation callers can be submitted in parallel as soon as they're created (that's what "--action qsub" would do), but the SomaticSeq scripts in RESULTS/[1,2,3...]/SomaticSeq/logs/sseq_*.cmd should only be submitted after each mutation caller job is complete. Without a workflow engine, those scripts are just created there, but need to be submitted manually. So "--action qsub" do not submit those scripts.
