### ISSUE TITLE
GATK4 Mutect2 

### ISSUE THREAD

**Issue by fpbarthel** [bioinform/somaticseq#65]
Hi!

Does somaticseq support GATK4 Mutect2 as well, as opposed to GATK3 MuTect2 which is mentioned in the documentation?

Thanks!

**Comment by ltfang-bina** [comment]
Actually SomaticSeq only supports GATK4's MuTect2. It doesn't really support GATK3's MuTect2, simply because SomaticSeq looks for two header lines in the VCF file that specifies which column is tumor and which column is normal (that only exists in GATK4 version). GATK3's MuTect2 has a different scheme.
