### ISSUE TITLE
stat /opt/somaticseq/utilities/split_mergedBed.py: no such file or directory error

### ISSUE THREAD

**Issue by jeongmeani** [bioinform/somaticseq#98]
Hi,

using Somatciseq version 3.4.0, i analysis WES data.
so far t have worked fine, but today some error occurs.

in docker space, running vardict like below script

`#!/bin/bash`

`#$ -o /data/projects/konyang/WES/03.Variant/1-2.Somaticseq_lofreq/pair/KY009-BL1.KY009-TT1/logs`
`#$ -e /data/projects/konyang/WES/03.Variant/1-2.Somaticseq_lofreq/pair/KY009-BL1.KY009-TT1/logs`
`#$ -S /bin/bash`
`#$ -l h_vmem=14G`
`set -e`

`echo -e "Start at date +"%Y/%m/%d %H:%M:%S"" 1>&2`

`docker run --rm -v /:/mnt -u $UID --memory 14G --cpu-shares 2048 lethalfang/somaticseq:latest \`
`/opt/somaticseq/utilities/split_mergedBed.py \`
`-infile /mnt//data/projects/konyang/WES/03.Variant/1-2.Somaticseq_lofreq/pair/KY009-BL1.KY009-TT1/genome.bed -outfile` `/mnt//data/projects/konyang/WES/03.Varia`

`docker run --rm -v /:/mnt -u $UID --memory 14G --cpu-shares 2048 lethalfang/vardictjava:1.7.0 bash -c \`
`"/opt/VarDict-1.7.0/bin/VarDict \`
`-G /mnt//data/ref/hg19/hg19.rm.superconfig.fa \`
`-f 0.05 -h \`
`-b '/mnt//data/projects/konyang/WES/02.BAM/6.Lofreq_indel/KY009`
`TT1.BQSR.lofreqIndel.bam|/mnt//data/projects/konyang/WES/02.BAM/6.Lofreq_indel/KY009-BL1.BQSR.`
`-Q 1 -c 1 -S 2 -E 3 -g 4 /mnt//data/projects/konyang/WES/03.Variant/1-2.Somaticseq_lofreq/pair/KY009-BL1.KY009-`TT1/split_regions.bed \`
`> /mnt//data/projects/konyang/WES/03.Variant/1-2.Somaticseq_lofreq/pair/KY009-BL1.KY009-TT1/vardict.var"`

`docker run --rm -v /:/mnt -u $UID --memory 14G --cpu-shares 2048 lethalfang/vardictjava:1.7.0 \`
`bash -c "cat /mnt//data/projects/konyang/WES/03.Variant/1-2.Somaticseq_lofreq/pair/KY009-BL1.KY009-TT1/vardict.var | awk `'NR!=1' | /opt/VarDict/testsomatic.R`
`> /mnt//data/projects/konyang/WES/03.Variant/1-2.Somaticseq_lofreq/pair/KY009-BL1.KY009-TT1/VarDict.vcf"`

`echo -e "Done at `date +"%Y/%m/%d %H:%M:%S"`" 1>&2`

but it returns error message

> container_linux.go:247: starting container process caused "exec: \"/opt/somaticseq/utilities/split_mergedBed.py\": stat >/opt/Bed.py: no such file or directory"

>docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: >\"/opedBed.py\": stat /opt/somaticseq/utilities/split_mergedBed.py: no such file or directory".

is this docker problem?

Best Regards.

Jeongmin

**Comment by litaifang** [comment]
I see. The problem is that in the latest docker image, I moved `somaticseq/utilities` into `somaticseq/somaticseq/utilities` to avoid potential namespace conflict, but the script is pulling `lethalfang/somaticseq:latest` while I should have used the same version as the version in the package, i.e., `lethalfang/somaticseq:3.4.0`. It never caused a problem until now. 
I think in all future versions, I'll fix the docker image version to the package version. For you though, I'm pretty sure if you manually change "latest" to "3.4.0", and reinstall, it'll fix the problem. 
I think there are two such instances:

- utilities/dockered_pipelines/create_tumor_normal_run_scripts.py
- utilities/dockered_pipelines/create_tumor_only_run_scripts.py

The lines are `out.write( 'docker run --rm -v /:/mnt -u $UID --memory {MEM}G lethalfang/somaticseq:{VERSION} \\\n'.format(MEM=mem, VERSION='latest') )`

**Comment by jeongmeani** [comment]
OK! 

Thank you for quick response and solution.

i have changed the version part of script, it works!

Thank you again.

Best Regards.

Jeongmin

**Comment by litaifang** [comment]
Older version pulling latest docker image: already solved as latest version will pull the docker image with the same version as the software version. For older installation, the solution may be manual.
